version: '3.8'

services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: cost-of-living-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cost_of_living
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  temporal:
    container_name: cost-of-living-temporal
    image: temporalio/admin-tools:1.24.2-tctl-1.18.1-cli-0.13.2
    networks:
      - default
    ports:
      - "7233:7233"
      - "8233:8233"
    entrypoint: /bin/sh
    command:
      - -c
      - "temporal server start-dev --ip 0.0.0.0 --ui-ip 0.0.0.0"

volumes:
  postgres_data:
  temporal-data:
